# Generated by Django 5.0.4 on 2024-04-28 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('학교', 'school'), ('회사', 'company'), ('가족', 'family'), ('친구', 'friend'), ('일과', 'daily')], default='daily', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_delete', models.BooleanField(default=False)),
                ('success', models.IntegerField()),
            ],
        ),
    ]
